// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logEventServer.proto

package enn.monitor.log.config.event.server;

public final class EnnMonitorLogConfigEventConnection {
  private EnnMonitorLogConfigEventConnection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protobuf/logEventServer.proto\032!protobu" +
      "f/logEventParameters.proto2\222\006\n\036EnnMonito" +
      "rLogConfigEventServer\022W\n\010GetEvent\022#.EnnM" +
      "onitorLogConfigEventGetRequest\032$.EnnMoni" +
      "torLogConfigEventGetResponse\"\000\022`\n\013Create" +
      "Event\022&.EnnMonitorLogConfigEventCreateRe" +
      "quest\032\'.EnnMonitorLogConfigEventCreateRe" +
      "sponse\"\000\022`\n\013UpdateEvent\022&.EnnMonitorLogC" +
      "onfigEventUpdateRequest\032\'.EnnMonitorLogC" +
      "onfigEventUpdateResponse\"\000\022`\n\013DeleteEven",
      "t\022&.EnnMonitorLogConfigEventDeleteReques" +
      "t\032\'.EnnMonitorLogConfigEventDeleteRespon" +
      "se\"\000\022u\n\022getMaxDeletedSeqNo\022-.EnnMonitorL" +
      "ogConfigEventGetMaxDeletedRequest\032..EnnM" +
      "onitorLogConfigEventGetMaxDeletedRespons" +
      "e\"\000\022y\n\020getValidDataList\0220.EnnMonitorLogC" +
      "onfigEventGetValidDataListRequest\0321.EnnM" +
      "onitorLogConfigEventGetValidDataListResp" +
      "onse\"\000\022\177\n\022getDeletedDataList\0222.EnnMonito" +
      "rLogConfigEventGetDeletedDataListRequest",
      "\0323.EnnMonitorLogConfigEventGetDeletedDat" +
      "aListResponse\"\000BK\n#enn.monitor.log.confi" +
      "g.event.serverB\"EnnMonitorLogConfigEvent" +
      "ConnectionP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          enn.monitor.log.config.event.parameters.EnnMonitorLogConfigEventParameters.getDescriptor(),
        }, assigner);
    enn.monitor.log.config.event.parameters.EnnMonitorLogConfigEventParameters.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
