// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/cluster.proto

package enn.monitor.config.cluster.cluster;

public final class EnnMonitorConfigClusterConnection {
  private EnnMonitorConfigClusterConnection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protobuf/cluster.proto\032 protobuf/clust" +
      "erParameters.proto2\235\007\n\035EnnMonitorConfigC" +
      "lusterServer\022W\n\nGetCluster\022\".EnnMonitorC" +
      "onfigClusterGetRequest\032#.EnnMonitorConfi" +
      "gClusterGetResponse\"\000\022`\n\rCreateCluster\022%" +
      ".EnnMonitorConfigClusterCreateRequest\032&." +
      "EnnMonitorConfigClusterCreateResponse\"\000\022" +
      "`\n\rUpdateCluster\022%.EnnMonitorConfigClust" +
      "erUpdateRequest\032&.EnnMonitorConfigCluste" +
      "rUpdateResponse\"\000\022`\n\rDeleteCluster\022%.Enn",
      "MonitorConfigClusterDeleteRequest\032&.EnnM" +
      "onitorConfigClusterDeleteResponse\"\000\022s\n\022g" +
      "etMaxDeletedSeqNo\022,.EnnMonitorConfigClus" +
      "terGetMaxDeletedRequest\032-.EnnMonitorConf" +
      "igClusterGetMaxDeletedResponse\"\000\022w\n\020getV" +
      "alidDataList\022/.EnnMonitorConfigClusterGe" +
      "tValidDataListRequest\0320.EnnMonitorConfig" +
      "ClusterGetValidDataListResponse\"\000\022}\n\022get" +
      "DeletedDataList\0221.EnnMonitorConfigCluste" +
      "rGetDeletedDataListRequest\0322.EnnMonitorC",
      "onfigClusterGetDeletedDataListResponse\"\000" +
      "\022\217\001\n\036checkClusterNameIsExistedOrNot\0224.En" +
      "nMonitorConfigClusterExistClusterNameOrN" +
      "otRequest\0325.EnnMonitorConfigClusterExist" +
      "ClusterNameOrNotResponse\"\000BI\n\"enn.monito" +
      "r.config.cluster.clusterB!EnnMonitorConf" +
      "igClusterConnectionP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterParameters.getDescriptor(),
        }, assigner);
    enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterParameters.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
