// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/topicParameters.proto

package enn.monitor.config.business.topic.parameters;

public interface EnnMonitorConfigBusinessTopicTableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorConfigBusinessTopicTable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional uint64 seqNo = 2;</code>
   */
  long getSeqNo();

  /**
   * <code>optional string source = 3;</code>
   */
  java.lang.String getSource();
  /**
   * <code>optional string source = 3;</code>
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>optional string topic = 4;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>optional string topic = 4;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>optional uint64 createTime = 5;</code>
   */
  long getCreateTime();

  /**
   * <code>optional uint64 lastUpdateTime = 6;</code>
   */
  long getLastUpdateTime();

  /**
   * <code>optional string createUser = 7;</code>
   */
  java.lang.String getCreateUser();
  /**
   * <code>optional string createUser = 7;</code>
   */
  com.google.protobuf.ByteString
      getCreateUserBytes();

  /**
   * <code>optional string lastUpdateUser = 8;</code>
   */
  java.lang.String getLastUpdateUser();
  /**
   * <code>optional string lastUpdateUser = 8;</code>
   */
  com.google.protobuf.ByteString
      getLastUpdateUserBytes();
}
