// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/topicParameters.proto

package enn.monitor.config.business.topic.parameters;

public interface EnnMonitorConfigBusinessTopicCreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorConfigBusinessTopicCreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>optional string error = 2;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
