// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/serviceLineParameters.proto

package enn.monitor.config.serviceLine.parameters;

/**
 * <pre>
 * get service line
 * </pre>
 *
 * Protobuf type {@code EnnMonitorConfigServiceLineGetRequest}
 */
public  final class EnnMonitorConfigServiceLineGetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnnMonitorConfigServiceLineGetRequest)
    EnnMonitorConfigServiceLineGetRequestOrBuilder {
  // Use EnnMonitorConfigServiceLineGetRequest.newBuilder() to construct.
  private EnnMonitorConfigServiceLineGetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnnMonitorConfigServiceLineGetRequest() {
    id_ = 0L;
    status_ = 0;
    serviceLineName_ = "";
    belongToCluster_ = 0L;
    createUser_ = "";
    lastUpdateUser_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EnnMonitorConfigServiceLineGetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readUInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceLineName_ = s;
            break;
          }
          case 32: {

            belongToCluster_ = input.readUInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            createUser_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            lastUpdateUser_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineParameters.internal_static_EnnMonitorConfigServiceLineGetRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineParameters.internal_static_EnnMonitorConfigServiceLineGetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest.class, enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>optional .EnnMonitorConfigServiceLineStatus status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>optional .EnnMonitorConfigServiceLineStatus status = 2;</code>
   */
  public enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus getStatus() {
    enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus result = enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus.valueOf(status_);
    return result == null ? enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus.UNRECOGNIZED : result;
  }

  public static final int SERVICELINENAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object serviceLineName_;
  /**
   * <code>optional string serviceLineName = 3;</code>
   */
  public java.lang.String getServiceLineName() {
    java.lang.Object ref = serviceLineName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceLineName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string serviceLineName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getServiceLineNameBytes() {
    java.lang.Object ref = serviceLineName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceLineName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BELONGTOCLUSTER_FIELD_NUMBER = 4;
  private long belongToCluster_;
  /**
   * <code>optional uint64 belongToCluster = 4;</code>
   */
  public long getBelongToCluster() {
    return belongToCluster_;
  }

  public static final int CREATEUSER_FIELD_NUMBER = 5;
  private volatile java.lang.Object createUser_;
  /**
   * <code>optional string createUser = 5;</code>
   */
  public java.lang.String getCreateUser() {
    java.lang.Object ref = createUser_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createUser_ = s;
      return s;
    }
  }
  /**
   * <code>optional string createUser = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCreateUserBytes() {
    java.lang.Object ref = createUser_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createUser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTUPDATEUSER_FIELD_NUMBER = 6;
  private volatile java.lang.Object lastUpdateUser_;
  /**
   * <code>optional string lastUpdateUser = 6;</code>
   */
  public java.lang.String getLastUpdateUser() {
    java.lang.Object ref = lastUpdateUser_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastUpdateUser_ = s;
      return s;
    }
  }
  /**
   * <code>optional string lastUpdateUser = 6;</code>
   */
  public com.google.protobuf.ByteString
      getLastUpdateUserBytes() {
    java.lang.Object ref = lastUpdateUser_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastUpdateUser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeUInt64(1, id_);
    }
    if (status_ != enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus.ServiceLineDefault.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (!getServiceLineNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serviceLineName_);
    }
    if (belongToCluster_ != 0L) {
      output.writeUInt64(4, belongToCluster_);
    }
    if (!getCreateUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, createUser_);
    }
    if (!getLastUpdateUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lastUpdateUser_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (status_ != enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus.ServiceLineDefault.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (!getServiceLineNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serviceLineName_);
    }
    if (belongToCluster_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, belongToCluster_);
    }
    if (!getCreateUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, createUser_);
    }
    if (!getLastUpdateUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lastUpdateUser_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest)) {
      return super.equals(obj);
    }
    enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest other = (enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && status_ == other.status_;
    result = result && getServiceLineName()
        .equals(other.getServiceLineName());
    result = result && (getBelongToCluster()
        == other.getBelongToCluster());
    result = result && getCreateUser()
        .equals(other.getCreateUser());
    result = result && getLastUpdateUser()
        .equals(other.getLastUpdateUser());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + SERVICELINENAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceLineName().hashCode();
    hash = (37 * hash) + BELONGTOCLUSTER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBelongToCluster());
    hash = (37 * hash) + CREATEUSER_FIELD_NUMBER;
    hash = (53 * hash) + getCreateUser().hashCode();
    hash = (37 * hash) + LASTUPDATEUSER_FIELD_NUMBER;
    hash = (53 * hash) + getLastUpdateUser().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * get service line
   * </pre>
   *
   * Protobuf type {@code EnnMonitorConfigServiceLineGetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnnMonitorConfigServiceLineGetRequest)
      enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineParameters.internal_static_EnnMonitorConfigServiceLineGetRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineParameters.internal_static_EnnMonitorConfigServiceLineGetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest.class, enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest.Builder.class);
    }

    // Construct using enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      status_ = 0;

      serviceLineName_ = "";

      belongToCluster_ = 0L;

      createUser_ = "";

      lastUpdateUser_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineParameters.internal_static_EnnMonitorConfigServiceLineGetRequest_descriptor;
    }

    public enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest getDefaultInstanceForType() {
      return enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest.getDefaultInstance();
    }

    public enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest build() {
      enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest buildPartial() {
      enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest result = new enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest(this);
      result.id_ = id_;
      result.status_ = status_;
      result.serviceLineName_ = serviceLineName_;
      result.belongToCluster_ = belongToCluster_;
      result.createUser_ = createUser_;
      result.lastUpdateUser_ = lastUpdateUser_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest) {
        return mergeFrom((enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest other) {
      if (other == enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getServiceLineName().isEmpty()) {
        serviceLineName_ = other.serviceLineName_;
        onChanged();
      }
      if (other.getBelongToCluster() != 0L) {
        setBelongToCluster(other.getBelongToCluster());
      }
      if (!other.getCreateUser().isEmpty()) {
        createUser_ = other.createUser_;
        onChanged();
      }
      if (!other.getLastUpdateUser().isEmpty()) {
        lastUpdateUser_ = other.lastUpdateUser_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>optional .EnnMonitorConfigServiceLineStatus status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .EnnMonitorConfigServiceLineStatus status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .EnnMonitorConfigServiceLineStatus status = 2;</code>
     */
    public enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus getStatus() {
      enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus result = enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus.valueOf(status_);
      return result == null ? enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .EnnMonitorConfigServiceLineStatus status = 2;</code>
     */
    public Builder setStatus(enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .EnnMonitorConfigServiceLineStatus status = 2;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object serviceLineName_ = "";
    /**
     * <code>optional string serviceLineName = 3;</code>
     */
    public java.lang.String getServiceLineName() {
      java.lang.Object ref = serviceLineName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceLineName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string serviceLineName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceLineNameBytes() {
      java.lang.Object ref = serviceLineName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceLineName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string serviceLineName = 3;</code>
     */
    public Builder setServiceLineName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceLineName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string serviceLineName = 3;</code>
     */
    public Builder clearServiceLineName() {
      
      serviceLineName_ = getDefaultInstance().getServiceLineName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string serviceLineName = 3;</code>
     */
    public Builder setServiceLineNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceLineName_ = value;
      onChanged();
      return this;
    }

    private long belongToCluster_ ;
    /**
     * <code>optional uint64 belongToCluster = 4;</code>
     */
    public long getBelongToCluster() {
      return belongToCluster_;
    }
    /**
     * <code>optional uint64 belongToCluster = 4;</code>
     */
    public Builder setBelongToCluster(long value) {
      
      belongToCluster_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 belongToCluster = 4;</code>
     */
    public Builder clearBelongToCluster() {
      
      belongToCluster_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object createUser_ = "";
    /**
     * <code>optional string createUser = 5;</code>
     */
    public java.lang.String getCreateUser() {
      java.lang.Object ref = createUser_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createUser_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string createUser = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCreateUserBytes() {
      java.lang.Object ref = createUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string createUser = 5;</code>
     */
    public Builder setCreateUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createUser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string createUser = 5;</code>
     */
    public Builder clearCreateUser() {
      
      createUser_ = getDefaultInstance().getCreateUser();
      onChanged();
      return this;
    }
    /**
     * <code>optional string createUser = 5;</code>
     */
    public Builder setCreateUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createUser_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastUpdateUser_ = "";
    /**
     * <code>optional string lastUpdateUser = 6;</code>
     */
    public java.lang.String getLastUpdateUser() {
      java.lang.Object ref = lastUpdateUser_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastUpdateUser_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string lastUpdateUser = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLastUpdateUserBytes() {
      java.lang.Object ref = lastUpdateUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastUpdateUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lastUpdateUser = 6;</code>
     */
    public Builder setLastUpdateUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastUpdateUser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastUpdateUser = 6;</code>
     */
    public Builder clearLastUpdateUser() {
      
      lastUpdateUser_ = getDefaultInstance().getLastUpdateUser();
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastUpdateUser = 6;</code>
     */
    public Builder setLastUpdateUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastUpdateUser_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EnnMonitorConfigServiceLineGetRequest)
  }

  // @@protoc_insertion_point(class_scope:EnnMonitorConfigServiceLineGetRequest)
  private static final enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest();
  }

  public static enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnnMonitorConfigServiceLineGetRequest>
      PARSER = new com.google.protobuf.AbstractParser<EnnMonitorConfigServiceLineGetRequest>() {
    public EnnMonitorConfigServiceLineGetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnnMonitorConfigServiceLineGetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnnMonitorConfigServiceLineGetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnnMonitorConfigServiceLineGetRequest> getParserForType() {
    return PARSER;
  }

  public enn.monitor.config.serviceLine.parameters.EnnMonitorConfigServiceLineGetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

