// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/normalizingParameters.proto

package enn.monitor.log.normalizing.parameters;

public interface EnnMonitorLogNormalizingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorLogNormalizingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>optional string result = 2;</code>
   */
  java.lang.String getResult();
  /**
   * <code>optional string result = 2;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>optional string error = 3;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
