// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/configEmailParameter.proto

package enn.monitor.alarm.config.email.parameter;

public interface EnnMonitorAlarmConfigEmailTableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorAlarmConfigEmailTable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional uint64 seqNo = 2;</code>
   */
  long getSeqNo();

  /**
   * <code>optional uint64 createTime = 3;</code>
   */
  long getCreateTime();

  /**
   * <code>optional uint64 lastUpdateTime = 4;</code>
   */
  long getLastUpdateTime();

  /**
   * <code>optional string createUser = 5;</code>
   */
  java.lang.String getCreateUser();
  /**
   * <code>optional string createUser = 5;</code>
   */
  com.google.protobuf.ByteString
      getCreateUserBytes();

  /**
   * <code>optional string lastUpdateUser = 6;</code>
   */
  java.lang.String getLastUpdateUser();
  /**
   * <code>optional string lastUpdateUser = 6;</code>
   */
  com.google.protobuf.ByteString
      getLastUpdateUserBytes();

  /**
   * <code>optional string groupName = 7;</code>
   */
  java.lang.String getGroupName();
  /**
   * <code>optional string groupName = 7;</code>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  /**
   * <code>optional string mail = 8;</code>
   */
  java.lang.String getMail();
  /**
   * <code>optional string mail = 8;</code>
   */
  com.google.protobuf.ByteString
      getMailBytes();

  /**
   * <code>optional string name = 9;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 9;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
