// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/configEmailParameter.proto

package enn.monitor.alarm.config.email.parameter;

public interface EnnMonitorAlarmConfigEmailUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorAlarmConfigEmailUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string groupName = 2;</code>
   */
  java.lang.String getGroupName();
  /**
   * <code>optional string groupName = 2;</code>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  /**
   * <code>optional string mail = 3;</code>
   */
  java.lang.String getMail();
  /**
   * <code>optional string mail = 3;</code>
   */
  com.google.protobuf.ByteString
      getMailBytes();

  /**
   * <code>optional string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string lastUpdateUser = 5;</code>
   */
  java.lang.String getLastUpdateUser();
  /**
   * <code>optional string lastUpdateUser = 5;</code>
   */
  com.google.protobuf.ByteString
      getLastUpdateUserBytes();
}
