// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/ticketParameter.proto

package enn.monitor.alarm.ticket.parameter;

public interface EnnMonitorAlarmTicketDeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorAlarmTicketDeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 1;</code>
   */
  long getId();
}
