// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/ticketParameter.proto

package enn.monitor.alarm.ticket.parameter;

/**
 * Protobuf type {@code EnnMonitorAlarmTicketGetRequest}
 */
public  final class EnnMonitorAlarmTicketGetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnnMonitorAlarmTicketGetRequest)
    EnnMonitorAlarmTicketGetRequestOrBuilder {
  // Use EnnMonitorAlarmTicketGetRequest.newBuilder() to construct.
  private EnnMonitorAlarmTicketGetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnnMonitorAlarmTicketGetRequest() {
    id_ = 0L;
    createUser_ = "";
    lastUpdateUser_ = "";
    ticketKey_ = "";
    ennMonitorAlarmTicketStatus_ = 0;
    ennMonitorAlarmTicketLevel_ = 0;
    grourName_ = "";
    clusterName_ = "";
    ip_ = "";
    nameSpace_ = "";
    podName_ = "";
    appName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EnnMonitorAlarmTicketGetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            createUser_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lastUpdateUser_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            ticketKey_ = s;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            ennMonitorAlarmTicketStatus_ = rawValue;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            ennMonitorAlarmTicketLevel_ = rawValue;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            grourName_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterName_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            nameSpace_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            podName_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            appName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketParameter.internal_static_EnnMonitorAlarmTicketGetRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketParameter.internal_static_EnnMonitorAlarmTicketGetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest.class, enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int CREATEUSER_FIELD_NUMBER = 2;
  private volatile java.lang.Object createUser_;
  /**
   * <code>optional string createUser = 2;</code>
   */
  public java.lang.String getCreateUser() {
    java.lang.Object ref = createUser_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createUser_ = s;
      return s;
    }
  }
  /**
   * <code>optional string createUser = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCreateUserBytes() {
    java.lang.Object ref = createUser_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createUser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTUPDATEUSER_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastUpdateUser_;
  /**
   * <code>optional string lastUpdateUser = 3;</code>
   */
  public java.lang.String getLastUpdateUser() {
    java.lang.Object ref = lastUpdateUser_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastUpdateUser_ = s;
      return s;
    }
  }
  /**
   * <code>optional string lastUpdateUser = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLastUpdateUserBytes() {
    java.lang.Object ref = lastUpdateUser_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastUpdateUser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TICKETKEY_FIELD_NUMBER = 4;
  private volatile java.lang.Object ticketKey_;
  /**
   * <code>optional string ticketKey = 4;</code>
   */
  public java.lang.String getTicketKey() {
    java.lang.Object ref = ticketKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ticketKey_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ticketKey = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTicketKeyBytes() {
    java.lang.Object ref = ticketKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ticketKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENNMONITORALARMTICKETSTATUS_FIELD_NUMBER = 5;
  private int ennMonitorAlarmTicketStatus_;
  /**
   * <code>optional .EnnMonitorAlarmTicketStatus ennMonitorAlarmTicketStatus = 5;</code>
   */
  public int getEnnMonitorAlarmTicketStatusValue() {
    return ennMonitorAlarmTicketStatus_;
  }
  /**
   * <code>optional .EnnMonitorAlarmTicketStatus ennMonitorAlarmTicketStatus = 5;</code>
   */
  public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus getEnnMonitorAlarmTicketStatus() {
    enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus result = enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus.valueOf(ennMonitorAlarmTicketStatus_);
    return result == null ? enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus.UNRECOGNIZED : result;
  }

  public static final int ENNMONITORALARMTICKETLEVEL_FIELD_NUMBER = 6;
  private int ennMonitorAlarmTicketLevel_;
  /**
   * <code>optional .EnnMonitorAlarmTicketLevel ennMonitorAlarmTicketLevel = 6;</code>
   */
  public int getEnnMonitorAlarmTicketLevelValue() {
    return ennMonitorAlarmTicketLevel_;
  }
  /**
   * <code>optional .EnnMonitorAlarmTicketLevel ennMonitorAlarmTicketLevel = 6;</code>
   */
  public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel getEnnMonitorAlarmTicketLevel() {
    enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel result = enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel.valueOf(ennMonitorAlarmTicketLevel_);
    return result == null ? enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel.UNRECOGNIZED : result;
  }

  public static final int GROURNAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object grourName_;
  /**
   * <code>optional string grourName = 7;</code>
   */
  public java.lang.String getGrourName() {
    java.lang.Object ref = grourName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      grourName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string grourName = 7;</code>
   */
  public com.google.protobuf.ByteString
      getGrourNameBytes() {
    java.lang.Object ref = grourName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      grourName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTERNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object clusterName_;
  /**
   * <code>optional string clusterName = 8;</code>
   */
  public java.lang.String getClusterName() {
    java.lang.Object ref = clusterName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string clusterName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getClusterNameBytes() {
    java.lang.Object ref = clusterName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 9;
  private volatile java.lang.Object ip_;
  /**
   * <code>optional string ip = 9;</code>
   */
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ip = 9;</code>
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMESPACE_FIELD_NUMBER = 10;
  private volatile java.lang.Object nameSpace_;
  /**
   * <code>optional string nameSpace = 10;</code>
   */
  public java.lang.String getNameSpace() {
    java.lang.Object ref = nameSpace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameSpace_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nameSpace = 10;</code>
   */
  public com.google.protobuf.ByteString
      getNameSpaceBytes() {
    java.lang.Object ref = nameSpace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameSpace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PODNAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object podName_;
  /**
   * <code>optional string podName = 11;</code>
   */
  public java.lang.String getPodName() {
    java.lang.Object ref = podName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      podName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string podName = 11;</code>
   */
  public com.google.protobuf.ByteString
      getPodNameBytes() {
    java.lang.Object ref = podName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      podName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPNAME_FIELD_NUMBER = 12;
  private volatile java.lang.Object appName_;
  /**
   * <code>optional string appName = 12;</code>
   */
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string appName = 12;</code>
   */
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeUInt64(1, id_);
    }
    if (!getCreateUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, createUser_);
    }
    if (!getLastUpdateUserBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastUpdateUser_);
    }
    if (!getTicketKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ticketKey_);
    }
    if (ennMonitorAlarmTicketStatus_ != enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus.EnnMonitorAlarmTicketStatusDefault.getNumber()) {
      output.writeEnum(5, ennMonitorAlarmTicketStatus_);
    }
    if (ennMonitorAlarmTicketLevel_ != enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel.EnnMonitorAlarmTicketLevelDefault.getNumber()) {
      output.writeEnum(6, ennMonitorAlarmTicketLevel_);
    }
    if (!getGrourNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, grourName_);
    }
    if (!getClusterNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, clusterName_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ip_);
    }
    if (!getNameSpaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, nameSpace_);
    }
    if (!getPodNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, podName_);
    }
    if (!getAppNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, appName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (!getCreateUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, createUser_);
    }
    if (!getLastUpdateUserBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastUpdateUser_);
    }
    if (!getTicketKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ticketKey_);
    }
    if (ennMonitorAlarmTicketStatus_ != enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus.EnnMonitorAlarmTicketStatusDefault.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, ennMonitorAlarmTicketStatus_);
    }
    if (ennMonitorAlarmTicketLevel_ != enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel.EnnMonitorAlarmTicketLevelDefault.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, ennMonitorAlarmTicketLevel_);
    }
    if (!getGrourNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, grourName_);
    }
    if (!getClusterNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, clusterName_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ip_);
    }
    if (!getNameSpaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, nameSpace_);
    }
    if (!getPodNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, podName_);
    }
    if (!getAppNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, appName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest)) {
      return super.equals(obj);
    }
    enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest other = (enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getCreateUser()
        .equals(other.getCreateUser());
    result = result && getLastUpdateUser()
        .equals(other.getLastUpdateUser());
    result = result && getTicketKey()
        .equals(other.getTicketKey());
    result = result && ennMonitorAlarmTicketStatus_ == other.ennMonitorAlarmTicketStatus_;
    result = result && ennMonitorAlarmTicketLevel_ == other.ennMonitorAlarmTicketLevel_;
    result = result && getGrourName()
        .equals(other.getGrourName());
    result = result && getClusterName()
        .equals(other.getClusterName());
    result = result && getIp()
        .equals(other.getIp());
    result = result && getNameSpace()
        .equals(other.getNameSpace());
    result = result && getPodName()
        .equals(other.getPodName());
    result = result && getAppName()
        .equals(other.getAppName());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + CREATEUSER_FIELD_NUMBER;
    hash = (53 * hash) + getCreateUser().hashCode();
    hash = (37 * hash) + LASTUPDATEUSER_FIELD_NUMBER;
    hash = (53 * hash) + getLastUpdateUser().hashCode();
    hash = (37 * hash) + TICKETKEY_FIELD_NUMBER;
    hash = (53 * hash) + getTicketKey().hashCode();
    hash = (37 * hash) + ENNMONITORALARMTICKETSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + ennMonitorAlarmTicketStatus_;
    hash = (37 * hash) + ENNMONITORALARMTICKETLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + ennMonitorAlarmTicketLevel_;
    hash = (37 * hash) + GROURNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGrourName().hashCode();
    hash = (37 * hash) + CLUSTERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClusterName().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNameSpace().hashCode();
    hash = (37 * hash) + PODNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPodName().hashCode();
    hash = (37 * hash) + APPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EnnMonitorAlarmTicketGetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnnMonitorAlarmTicketGetRequest)
      enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketParameter.internal_static_EnnMonitorAlarmTicketGetRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketParameter.internal_static_EnnMonitorAlarmTicketGetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest.class, enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest.Builder.class);
    }

    // Construct using enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      createUser_ = "";

      lastUpdateUser_ = "";

      ticketKey_ = "";

      ennMonitorAlarmTicketStatus_ = 0;

      ennMonitorAlarmTicketLevel_ = 0;

      grourName_ = "";

      clusterName_ = "";

      ip_ = "";

      nameSpace_ = "";

      podName_ = "";

      appName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketParameter.internal_static_EnnMonitorAlarmTicketGetRequest_descriptor;
    }

    public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest getDefaultInstanceForType() {
      return enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest.getDefaultInstance();
    }

    public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest build() {
      enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest buildPartial() {
      enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest result = new enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest(this);
      result.id_ = id_;
      result.createUser_ = createUser_;
      result.lastUpdateUser_ = lastUpdateUser_;
      result.ticketKey_ = ticketKey_;
      result.ennMonitorAlarmTicketStatus_ = ennMonitorAlarmTicketStatus_;
      result.ennMonitorAlarmTicketLevel_ = ennMonitorAlarmTicketLevel_;
      result.grourName_ = grourName_;
      result.clusterName_ = clusterName_;
      result.ip_ = ip_;
      result.nameSpace_ = nameSpace_;
      result.podName_ = podName_;
      result.appName_ = appName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest) {
        return mergeFrom((enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest other) {
      if (other == enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getCreateUser().isEmpty()) {
        createUser_ = other.createUser_;
        onChanged();
      }
      if (!other.getLastUpdateUser().isEmpty()) {
        lastUpdateUser_ = other.lastUpdateUser_;
        onChanged();
      }
      if (!other.getTicketKey().isEmpty()) {
        ticketKey_ = other.ticketKey_;
        onChanged();
      }
      if (other.ennMonitorAlarmTicketStatus_ != 0) {
        setEnnMonitorAlarmTicketStatusValue(other.getEnnMonitorAlarmTicketStatusValue());
      }
      if (other.ennMonitorAlarmTicketLevel_ != 0) {
        setEnnMonitorAlarmTicketLevelValue(other.getEnnMonitorAlarmTicketLevelValue());
      }
      if (!other.getGrourName().isEmpty()) {
        grourName_ = other.grourName_;
        onChanged();
      }
      if (!other.getClusterName().isEmpty()) {
        clusterName_ = other.clusterName_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (!other.getNameSpace().isEmpty()) {
        nameSpace_ = other.nameSpace_;
        onChanged();
      }
      if (!other.getPodName().isEmpty()) {
        podName_ = other.podName_;
        onChanged();
      }
      if (!other.getAppName().isEmpty()) {
        appName_ = other.appName_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object createUser_ = "";
    /**
     * <code>optional string createUser = 2;</code>
     */
    public java.lang.String getCreateUser() {
      java.lang.Object ref = createUser_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createUser_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string createUser = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreateUserBytes() {
      java.lang.Object ref = createUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string createUser = 2;</code>
     */
    public Builder setCreateUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createUser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string createUser = 2;</code>
     */
    public Builder clearCreateUser() {
      
      createUser_ = getDefaultInstance().getCreateUser();
      onChanged();
      return this;
    }
    /**
     * <code>optional string createUser = 2;</code>
     */
    public Builder setCreateUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createUser_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastUpdateUser_ = "";
    /**
     * <code>optional string lastUpdateUser = 3;</code>
     */
    public java.lang.String getLastUpdateUser() {
      java.lang.Object ref = lastUpdateUser_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastUpdateUser_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string lastUpdateUser = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastUpdateUserBytes() {
      java.lang.Object ref = lastUpdateUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastUpdateUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lastUpdateUser = 3;</code>
     */
    public Builder setLastUpdateUser(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastUpdateUser_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastUpdateUser = 3;</code>
     */
    public Builder clearLastUpdateUser() {
      
      lastUpdateUser_ = getDefaultInstance().getLastUpdateUser();
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastUpdateUser = 3;</code>
     */
    public Builder setLastUpdateUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastUpdateUser_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ticketKey_ = "";
    /**
     * <code>optional string ticketKey = 4;</code>
     */
    public java.lang.String getTicketKey() {
      java.lang.Object ref = ticketKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticketKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ticketKey = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTicketKeyBytes() {
      java.lang.Object ref = ticketKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticketKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ticketKey = 4;</code>
     */
    public Builder setTicketKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ticketKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ticketKey = 4;</code>
     */
    public Builder clearTicketKey() {
      
      ticketKey_ = getDefaultInstance().getTicketKey();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ticketKey = 4;</code>
     */
    public Builder setTicketKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ticketKey_ = value;
      onChanged();
      return this;
    }

    private int ennMonitorAlarmTicketStatus_ = 0;
    /**
     * <code>optional .EnnMonitorAlarmTicketStatus ennMonitorAlarmTicketStatus = 5;</code>
     */
    public int getEnnMonitorAlarmTicketStatusValue() {
      return ennMonitorAlarmTicketStatus_;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketStatus ennMonitorAlarmTicketStatus = 5;</code>
     */
    public Builder setEnnMonitorAlarmTicketStatusValue(int value) {
      ennMonitorAlarmTicketStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketStatus ennMonitorAlarmTicketStatus = 5;</code>
     */
    public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus getEnnMonitorAlarmTicketStatus() {
      enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus result = enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus.valueOf(ennMonitorAlarmTicketStatus_);
      return result == null ? enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketStatus ennMonitorAlarmTicketStatus = 5;</code>
     */
    public Builder setEnnMonitorAlarmTicketStatus(enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ennMonitorAlarmTicketStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketStatus ennMonitorAlarmTicketStatus = 5;</code>
     */
    public Builder clearEnnMonitorAlarmTicketStatus() {
      
      ennMonitorAlarmTicketStatus_ = 0;
      onChanged();
      return this;
    }

    private int ennMonitorAlarmTicketLevel_ = 0;
    /**
     * <code>optional .EnnMonitorAlarmTicketLevel ennMonitorAlarmTicketLevel = 6;</code>
     */
    public int getEnnMonitorAlarmTicketLevelValue() {
      return ennMonitorAlarmTicketLevel_;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketLevel ennMonitorAlarmTicketLevel = 6;</code>
     */
    public Builder setEnnMonitorAlarmTicketLevelValue(int value) {
      ennMonitorAlarmTicketLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketLevel ennMonitorAlarmTicketLevel = 6;</code>
     */
    public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel getEnnMonitorAlarmTicketLevel() {
      enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel result = enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel.valueOf(ennMonitorAlarmTicketLevel_);
      return result == null ? enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketLevel ennMonitorAlarmTicketLevel = 6;</code>
     */
    public Builder setEnnMonitorAlarmTicketLevel(enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketLevel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ennMonitorAlarmTicketLevel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .EnnMonitorAlarmTicketLevel ennMonitorAlarmTicketLevel = 6;</code>
     */
    public Builder clearEnnMonitorAlarmTicketLevel() {
      
      ennMonitorAlarmTicketLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object grourName_ = "";
    /**
     * <code>optional string grourName = 7;</code>
     */
    public java.lang.String getGrourName() {
      java.lang.Object ref = grourName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grourName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string grourName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGrourNameBytes() {
      java.lang.Object ref = grourName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grourName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string grourName = 7;</code>
     */
    public Builder setGrourName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      grourName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string grourName = 7;</code>
     */
    public Builder clearGrourName() {
      
      grourName_ = getDefaultInstance().getGrourName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string grourName = 7;</code>
     */
    public Builder setGrourNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      grourName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clusterName_ = "";
    /**
     * <code>optional string clusterName = 8;</code>
     */
    public java.lang.String getClusterName() {
      java.lang.Object ref = clusterName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string clusterName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getClusterNameBytes() {
      java.lang.Object ref = clusterName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string clusterName = 8;</code>
     */
    public Builder setClusterName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string clusterName = 8;</code>
     */
    public Builder clearClusterName() {
      
      clusterName_ = getDefaultInstance().getClusterName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string clusterName = 8;</code>
     */
    public Builder setClusterNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ip_ = "";
    /**
     * <code>optional string ip = 9;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ip = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ip = 9;</code>
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ip = 9;</code>
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>optional string ip = 9;</code>
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameSpace_ = "";
    /**
     * <code>optional string nameSpace = 10;</code>
     */
    public java.lang.String getNameSpace() {
      java.lang.Object ref = nameSpace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameSpace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nameSpace = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNameSpaceBytes() {
      java.lang.Object ref = nameSpace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameSpace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nameSpace = 10;</code>
     */
    public Builder setNameSpace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameSpace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nameSpace = 10;</code>
     */
    public Builder clearNameSpace() {
      
      nameSpace_ = getDefaultInstance().getNameSpace();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nameSpace = 10;</code>
     */
    public Builder setNameSpaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameSpace_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object podName_ = "";
    /**
     * <code>optional string podName = 11;</code>
     */
    public java.lang.String getPodName() {
      java.lang.Object ref = podName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        podName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string podName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPodNameBytes() {
      java.lang.Object ref = podName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        podName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string podName = 11;</code>
     */
    public Builder setPodName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      podName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string podName = 11;</code>
     */
    public Builder clearPodName() {
      
      podName_ = getDefaultInstance().getPodName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string podName = 11;</code>
     */
    public Builder setPodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      podName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appName_ = "";
    /**
     * <code>optional string appName = 12;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string appName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string appName = 12;</code>
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string appName = 12;</code>
     */
    public Builder clearAppName() {
      
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string appName = 12;</code>
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EnnMonitorAlarmTicketGetRequest)
  }

  // @@protoc_insertion_point(class_scope:EnnMonitorAlarmTicketGetRequest)
  private static final enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest();
  }

  public static enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnnMonitorAlarmTicketGetRequest>
      PARSER = new com.google.protobuf.AbstractParser<EnnMonitorAlarmTicketGetRequest>() {
    public EnnMonitorAlarmTicketGetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnnMonitorAlarmTicketGetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnnMonitorAlarmTicketGetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnnMonitorAlarmTicketGetRequest> getParserForType() {
    return PARSER;
  }

  public enn.monitor.alarm.ticket.parameter.EnnMonitorAlarmTicketGetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

