// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/trainParameters.proto

package enn.monitor.log.train.proto;

/**
 * Protobuf type {@code EnnMonitorLogTrainMasterReportJobStatusReq}
 */
public  final class EnnMonitorLogTrainMasterReportJobStatusReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnnMonitorLogTrainMasterReportJobStatusReq)
    EnnMonitorLogTrainMasterReportJobStatusReqOrBuilder {
  // Use EnnMonitorLogTrainMasterReportJobStatusReq.newBuilder() to construct.
  private EnnMonitorLogTrainMasterReportJobStatusReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnnMonitorLogTrainMasterReportJobStatusReq() {
    jobStatus_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EnnMonitorLogTrainMasterReportJobStatusReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              jobStatus_ = new java.util.ArrayList<enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobStatus_.add(
                input.readMessage(enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        jobStatus_ = java.util.Collections.unmodifiableList(jobStatus_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainMasterReportJobStatusReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainMasterReportJobStatusReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq.class, enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq.Builder.class);
  }

  public static final int JOBSTATUS_FIELD_NUMBER = 1;
  private java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus> jobStatus_;
  /**
   * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
   */
  public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus> getJobStatusList() {
    return jobStatus_;
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
   */
  public java.util.List<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatusOrBuilder> 
      getJobStatusOrBuilderList() {
    return jobStatus_;
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
   */
  public int getJobStatusCount() {
    return jobStatus_.size();
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
   */
  public enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus getJobStatus(int index) {
    return jobStatus_.get(index);
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
   */
  public enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatusOrBuilder getJobStatusOrBuilder(
      int index) {
    return jobStatus_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobStatus_.size(); i++) {
      output.writeMessage(1, jobStatus_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobStatus_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobStatus_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq)) {
      return super.equals(obj);
    }
    enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq other = (enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq) obj;

    boolean result = true;
    result = result && getJobStatusList()
        .equals(other.getJobStatusList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getJobStatusCount() > 0) {
      hash = (37 * hash) + JOBSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getJobStatusList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EnnMonitorLogTrainMasterReportJobStatusReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnnMonitorLogTrainMasterReportJobStatusReq)
      enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainMasterReportJobStatusReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainMasterReportJobStatusReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq.class, enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq.Builder.class);
    }

    // Construct using enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobStatusFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (jobStatusBuilder_ == null) {
        jobStatus_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobStatusBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainMasterReportJobStatusReq_descriptor;
    }

    public enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq getDefaultInstanceForType() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq.getDefaultInstance();
    }

    public enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq build() {
      enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq buildPartial() {
      enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq result = new enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq(this);
      int from_bitField0_ = bitField0_;
      if (jobStatusBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          jobStatus_ = java.util.Collections.unmodifiableList(jobStatus_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobStatus_ = jobStatus_;
      } else {
        result.jobStatus_ = jobStatusBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq) {
        return mergeFrom((enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq other) {
      if (other == enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq.getDefaultInstance()) return this;
      if (jobStatusBuilder_ == null) {
        if (!other.jobStatus_.isEmpty()) {
          if (jobStatus_.isEmpty()) {
            jobStatus_ = other.jobStatus_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobStatusIsMutable();
            jobStatus_.addAll(other.jobStatus_);
          }
          onChanged();
        }
      } else {
        if (!other.jobStatus_.isEmpty()) {
          if (jobStatusBuilder_.isEmpty()) {
            jobStatusBuilder_.dispose();
            jobStatusBuilder_ = null;
            jobStatus_ = other.jobStatus_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobStatusBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobStatusFieldBuilder() : null;
          } else {
            jobStatusBuilder_.addAllMessages(other.jobStatus_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus> jobStatus_ =
      java.util.Collections.emptyList();
    private void ensureJobStatusIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        jobStatus_ = new java.util.ArrayList<enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus>(jobStatus_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatusOrBuilder> jobStatusBuilder_;

    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus> getJobStatusList() {
      if (jobStatusBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobStatus_);
      } else {
        return jobStatusBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public int getJobStatusCount() {
      if (jobStatusBuilder_ == null) {
        return jobStatus_.size();
      } else {
        return jobStatusBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus getJobStatus(int index) {
      if (jobStatusBuilder_ == null) {
        return jobStatus_.get(index);
      } else {
        return jobStatusBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder setJobStatus(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus value) {
      if (jobStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobStatusIsMutable();
        jobStatus_.set(index, value);
        onChanged();
      } else {
        jobStatusBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder setJobStatus(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder builderForValue) {
      if (jobStatusBuilder_ == null) {
        ensureJobStatusIsMutable();
        jobStatus_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobStatusBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder addJobStatus(enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus value) {
      if (jobStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobStatusIsMutable();
        jobStatus_.add(value);
        onChanged();
      } else {
        jobStatusBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder addJobStatus(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus value) {
      if (jobStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobStatusIsMutable();
        jobStatus_.add(index, value);
        onChanged();
      } else {
        jobStatusBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder addJobStatus(
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder builderForValue) {
      if (jobStatusBuilder_ == null) {
        ensureJobStatusIsMutable();
        jobStatus_.add(builderForValue.build());
        onChanged();
      } else {
        jobStatusBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder addJobStatus(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder builderForValue) {
      if (jobStatusBuilder_ == null) {
        ensureJobStatusIsMutable();
        jobStatus_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobStatusBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder addAllJobStatus(
        java.lang.Iterable<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus> values) {
      if (jobStatusBuilder_ == null) {
        ensureJobStatusIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobStatus_);
        onChanged();
      } else {
        jobStatusBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder clearJobStatus() {
      if (jobStatusBuilder_ == null) {
        jobStatus_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobStatusBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public Builder removeJobStatus(int index) {
      if (jobStatusBuilder_ == null) {
        ensureJobStatusIsMutable();
        jobStatus_.remove(index);
        onChanged();
      } else {
        jobStatusBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder getJobStatusBuilder(
        int index) {
      return getJobStatusFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatusOrBuilder getJobStatusOrBuilder(
        int index) {
      if (jobStatusBuilder_ == null) {
        return jobStatus_.get(index);  } else {
        return jobStatusBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public java.util.List<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatusOrBuilder> 
         getJobStatusOrBuilderList() {
      if (jobStatusBuilder_ != null) {
        return jobStatusBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobStatus_);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder addJobStatusBuilder() {
      return getJobStatusFieldBuilder().addBuilder(
          enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder addJobStatusBuilder(
        int index) {
      return getJobStatusFieldBuilder().addBuilder(
          index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobStatus jobStatus = 1;</code>
     */
    public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder> 
         getJobStatusBuilderList() {
      return getJobStatusFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatusOrBuilder> 
        getJobStatusFieldBuilder() {
      if (jobStatusBuilder_ == null) {
        jobStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatus.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobStatusOrBuilder>(
                jobStatus_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        jobStatus_ = null;
      }
      return jobStatusBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EnnMonitorLogTrainMasterReportJobStatusReq)
  }

  // @@protoc_insertion_point(class_scope:EnnMonitorLogTrainMasterReportJobStatusReq)
  private static final enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq();
  }

  public static enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnnMonitorLogTrainMasterReportJobStatusReq>
      PARSER = new com.google.protobuf.AbstractParser<EnnMonitorLogTrainMasterReportJobStatusReq>() {
    public EnnMonitorLogTrainMasterReportJobStatusReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnnMonitorLogTrainMasterReportJobStatusReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnnMonitorLogTrainMasterReportJobStatusReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnnMonitorLogTrainMasterReportJobStatusReq> getParserForType() {
    return PARSER;
  }

  public enn.monitor.log.train.proto.EnnMonitorLogTrainMasterReportJobStatusReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

