// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/trainParameters.proto

package enn.monitor.log.train.proto;

/**
 * Protobuf type {@code EnnMonitorLogTrainJob}
 */
public  final class EnnMonitorLogTrainJob extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnnMonitorLogTrainJob)
    EnnMonitorLogTrainJobOrBuilder {
  // Use EnnMonitorLogTrainJob.newBuilder() to construct.
  private EnnMonitorLogTrainJob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnnMonitorLogTrainJob() {
    jobId_ = 0L;
    job_ = "";
    genomNum_ = 0L;
    returnBestNum_ = 0L;
    changeParameter_ = 0L;
    eliteGenerator_ = 0L;
    input_ = java.util.Collections.emptyList();
    output_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EnnMonitorLogTrainJob(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            jobId_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            job_ = s;
            break;
          }
          case 24: {

            genomNum_ = input.readUInt64();
            break;
          }
          case 32: {

            returnBestNum_ = input.readUInt64();
            break;
          }
          case 40: {

            changeParameter_ = input.readUInt64();
            break;
          }
          case 48: {

            eliteGenerator_ = input.readUInt64();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              input_ = new java.util.ArrayList<enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput>();
              mutable_bitField0_ |= 0x00000040;
            }
            input_.add(
                input.readMessage(enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.parser(), extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              output_ = new java.util.ArrayList<enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput>();
              mutable_bitField0_ |= 0x00000080;
            }
            output_.add(
                input.readMessage(enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        input_ = java.util.Collections.unmodifiableList(input_);
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        output_ = java.util.Collections.unmodifiableList(output_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainJob_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainJob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            enn.monitor.log.train.proto.EnnMonitorLogTrainJob.class, enn.monitor.log.train.proto.EnnMonitorLogTrainJob.Builder.class);
  }

  private int bitField0_;
  public static final int JOBID_FIELD_NUMBER = 1;
  private long jobId_;
  /**
   * <code>optional uint64 jobId = 1;</code>
   */
  public long getJobId() {
    return jobId_;
  }

  public static final int JOB_FIELD_NUMBER = 2;
  private volatile java.lang.Object job_;
  /**
   * <code>optional string job = 2;</code>
   */
  public java.lang.String getJob() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      job_ = s;
      return s;
    }
  }
  /**
   * <code>optional string job = 2;</code>
   */
  public com.google.protobuf.ByteString
      getJobBytes() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      job_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENOMNUM_FIELD_NUMBER = 3;
  private long genomNum_;
  /**
   * <code>optional uint64 genomNum = 3;</code>
   */
  public long getGenomNum() {
    return genomNum_;
  }

  public static final int RETURNBESTNUM_FIELD_NUMBER = 4;
  private long returnBestNum_;
  /**
   * <code>optional uint64 returnBestNum = 4;</code>
   */
  public long getReturnBestNum() {
    return returnBestNum_;
  }

  public static final int CHANGEPARAMETER_FIELD_NUMBER = 5;
  private long changeParameter_;
  /**
   * <code>optional uint64 changeParameter = 5;</code>
   */
  public long getChangeParameter() {
    return changeParameter_;
  }

  public static final int ELITEGENERATOR_FIELD_NUMBER = 6;
  private long eliteGenerator_;
  /**
   * <code>optional uint64 eliteGenerator = 6;</code>
   */
  public long getEliteGenerator() {
    return eliteGenerator_;
  }

  public static final int INPUT_FIELD_NUMBER = 7;
  private java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput> input_;
  /**
   * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
   */
  public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput> getInputList() {
    return input_;
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
   */
  public java.util.List<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobInputOrBuilder> 
      getInputOrBuilderList() {
    return input_;
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
   */
  public int getInputCount() {
    return input_.size();
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
   */
  public enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput getInput(int index) {
    return input_.get(index);
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
   */
  public enn.monitor.log.train.proto.EnnMonitorLogTrainJobInputOrBuilder getInputOrBuilder(
      int index) {
    return input_.get(index);
  }

  public static final int OUTPUT_FIELD_NUMBER = 8;
  private java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput> output_;
  /**
   * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
   */
  public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput> getOutputList() {
    return output_;
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
   */
  public java.util.List<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutputOrBuilder> 
      getOutputOrBuilderList() {
    return output_;
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
   */
  public int getOutputCount() {
    return output_.size();
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
   */
  public enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput getOutput(int index) {
    return output_.get(index);
  }
  /**
   * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
   */
  public enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutputOrBuilder getOutputOrBuilder(
      int index) {
    return output_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (jobId_ != 0L) {
      output.writeUInt64(1, jobId_);
    }
    if (!getJobBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, job_);
    }
    if (genomNum_ != 0L) {
      output.writeUInt64(3, genomNum_);
    }
    if (returnBestNum_ != 0L) {
      output.writeUInt64(4, returnBestNum_);
    }
    if (changeParameter_ != 0L) {
      output.writeUInt64(5, changeParameter_);
    }
    if (eliteGenerator_ != 0L) {
      output.writeUInt64(6, eliteGenerator_);
    }
    for (int i = 0; i < input_.size(); i++) {
      output.writeMessage(7, input_.get(i));
    }
    for (int i = 0; i < output_.size(); i++) {
      output.writeMessage(8, output_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (jobId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, jobId_);
    }
    if (!getJobBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, job_);
    }
    if (genomNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, genomNum_);
    }
    if (returnBestNum_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, returnBestNum_);
    }
    if (changeParameter_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, changeParameter_);
    }
    if (eliteGenerator_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, eliteGenerator_);
    }
    for (int i = 0; i < input_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, input_.get(i));
    }
    for (int i = 0; i < output_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, output_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof enn.monitor.log.train.proto.EnnMonitorLogTrainJob)) {
      return super.equals(obj);
    }
    enn.monitor.log.train.proto.EnnMonitorLogTrainJob other = (enn.monitor.log.train.proto.EnnMonitorLogTrainJob) obj;

    boolean result = true;
    result = result && (getJobId()
        == other.getJobId());
    result = result && getJob()
        .equals(other.getJob());
    result = result && (getGenomNum()
        == other.getGenomNum());
    result = result && (getReturnBestNum()
        == other.getReturnBestNum());
    result = result && (getChangeParameter()
        == other.getChangeParameter());
    result = result && (getEliteGenerator()
        == other.getEliteGenerator());
    result = result && getInputList()
        .equals(other.getInputList());
    result = result && getOutputList()
        .equals(other.getOutputList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + JOBID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getJobId());
    hash = (37 * hash) + JOB_FIELD_NUMBER;
    hash = (53 * hash) + getJob().hashCode();
    hash = (37 * hash) + GENOMNUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGenomNum());
    hash = (37 * hash) + RETURNBESTNUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReturnBestNum());
    hash = (37 * hash) + CHANGEPARAMETER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChangeParameter());
    hash = (37 * hash) + ELITEGENERATOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEliteGenerator());
    if (getInputCount() > 0) {
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInputList().hashCode();
    }
    if (getOutputCount() > 0) {
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutputList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(enn.monitor.log.train.proto.EnnMonitorLogTrainJob prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EnnMonitorLogTrainJob}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnnMonitorLogTrainJob)
      enn.monitor.log.train.proto.EnnMonitorLogTrainJobOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainJob_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainJob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              enn.monitor.log.train.proto.EnnMonitorLogTrainJob.class, enn.monitor.log.train.proto.EnnMonitorLogTrainJob.Builder.class);
    }

    // Construct using enn.monitor.log.train.proto.EnnMonitorLogTrainJob.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInputFieldBuilder();
        getOutputFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      jobId_ = 0L;

      job_ = "";

      genomNum_ = 0L;

      returnBestNum_ = 0L;

      changeParameter_ = 0L;

      eliteGenerator_ = 0L;

      if (inputBuilder_ == null) {
        input_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        inputBuilder_.clear();
      }
      if (outputBuilder_ == null) {
        output_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        outputBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainParameters.internal_static_EnnMonitorLogTrainJob_descriptor;
    }

    public enn.monitor.log.train.proto.EnnMonitorLogTrainJob getDefaultInstanceForType() {
      return enn.monitor.log.train.proto.EnnMonitorLogTrainJob.getDefaultInstance();
    }

    public enn.monitor.log.train.proto.EnnMonitorLogTrainJob build() {
      enn.monitor.log.train.proto.EnnMonitorLogTrainJob result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public enn.monitor.log.train.proto.EnnMonitorLogTrainJob buildPartial() {
      enn.monitor.log.train.proto.EnnMonitorLogTrainJob result = new enn.monitor.log.train.proto.EnnMonitorLogTrainJob(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.jobId_ = jobId_;
      result.job_ = job_;
      result.genomNum_ = genomNum_;
      result.returnBestNum_ = returnBestNum_;
      result.changeParameter_ = changeParameter_;
      result.eliteGenerator_ = eliteGenerator_;
      if (inputBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          input_ = java.util.Collections.unmodifiableList(input_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.input_ = input_;
      } else {
        result.input_ = inputBuilder_.build();
      }
      if (outputBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output_ = java.util.Collections.unmodifiableList(output_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.output_ = output_;
      } else {
        result.output_ = outputBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof enn.monitor.log.train.proto.EnnMonitorLogTrainJob) {
        return mergeFrom((enn.monitor.log.train.proto.EnnMonitorLogTrainJob)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(enn.monitor.log.train.proto.EnnMonitorLogTrainJob other) {
      if (other == enn.monitor.log.train.proto.EnnMonitorLogTrainJob.getDefaultInstance()) return this;
      if (other.getJobId() != 0L) {
        setJobId(other.getJobId());
      }
      if (!other.getJob().isEmpty()) {
        job_ = other.job_;
        onChanged();
      }
      if (other.getGenomNum() != 0L) {
        setGenomNum(other.getGenomNum());
      }
      if (other.getReturnBestNum() != 0L) {
        setReturnBestNum(other.getReturnBestNum());
      }
      if (other.getChangeParameter() != 0L) {
        setChangeParameter(other.getChangeParameter());
      }
      if (other.getEliteGenerator() != 0L) {
        setEliteGenerator(other.getEliteGenerator());
      }
      if (inputBuilder_ == null) {
        if (!other.input_.isEmpty()) {
          if (input_.isEmpty()) {
            input_ = other.input_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureInputIsMutable();
            input_.addAll(other.input_);
          }
          onChanged();
        }
      } else {
        if (!other.input_.isEmpty()) {
          if (inputBuilder_.isEmpty()) {
            inputBuilder_.dispose();
            inputBuilder_ = null;
            input_ = other.input_;
            bitField0_ = (bitField0_ & ~0x00000040);
            inputBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInputFieldBuilder() : null;
          } else {
            inputBuilder_.addAllMessages(other.input_);
          }
        }
      }
      if (outputBuilder_ == null) {
        if (!other.output_.isEmpty()) {
          if (output_.isEmpty()) {
            output_ = other.output_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureOutputIsMutable();
            output_.addAll(other.output_);
          }
          onChanged();
        }
      } else {
        if (!other.output_.isEmpty()) {
          if (outputBuilder_.isEmpty()) {
            outputBuilder_.dispose();
            outputBuilder_ = null;
            output_ = other.output_;
            bitField0_ = (bitField0_ & ~0x00000080);
            outputBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOutputFieldBuilder() : null;
          } else {
            outputBuilder_.addAllMessages(other.output_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      enn.monitor.log.train.proto.EnnMonitorLogTrainJob parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (enn.monitor.log.train.proto.EnnMonitorLogTrainJob) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long jobId_ ;
    /**
     * <code>optional uint64 jobId = 1;</code>
     */
    public long getJobId() {
      return jobId_;
    }
    /**
     * <code>optional uint64 jobId = 1;</code>
     */
    public Builder setJobId(long value) {
      
      jobId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 jobId = 1;</code>
     */
    public Builder clearJobId() {
      
      jobId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object job_ = "";
    /**
     * <code>optional string job = 2;</code>
     */
    public java.lang.String getJob() {
      java.lang.Object ref = job_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        job_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string job = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJobBytes() {
      java.lang.Object ref = job_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        job_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string job = 2;</code>
     */
    public Builder setJob(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      job_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string job = 2;</code>
     */
    public Builder clearJob() {
      
      job_ = getDefaultInstance().getJob();
      onChanged();
      return this;
    }
    /**
     * <code>optional string job = 2;</code>
     */
    public Builder setJobBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      job_ = value;
      onChanged();
      return this;
    }

    private long genomNum_ ;
    /**
     * <code>optional uint64 genomNum = 3;</code>
     */
    public long getGenomNum() {
      return genomNum_;
    }
    /**
     * <code>optional uint64 genomNum = 3;</code>
     */
    public Builder setGenomNum(long value) {
      
      genomNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 genomNum = 3;</code>
     */
    public Builder clearGenomNum() {
      
      genomNum_ = 0L;
      onChanged();
      return this;
    }

    private long returnBestNum_ ;
    /**
     * <code>optional uint64 returnBestNum = 4;</code>
     */
    public long getReturnBestNum() {
      return returnBestNum_;
    }
    /**
     * <code>optional uint64 returnBestNum = 4;</code>
     */
    public Builder setReturnBestNum(long value) {
      
      returnBestNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 returnBestNum = 4;</code>
     */
    public Builder clearReturnBestNum() {
      
      returnBestNum_ = 0L;
      onChanged();
      return this;
    }

    private long changeParameter_ ;
    /**
     * <code>optional uint64 changeParameter = 5;</code>
     */
    public long getChangeParameter() {
      return changeParameter_;
    }
    /**
     * <code>optional uint64 changeParameter = 5;</code>
     */
    public Builder setChangeParameter(long value) {
      
      changeParameter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 changeParameter = 5;</code>
     */
    public Builder clearChangeParameter() {
      
      changeParameter_ = 0L;
      onChanged();
      return this;
    }

    private long eliteGenerator_ ;
    /**
     * <code>optional uint64 eliteGenerator = 6;</code>
     */
    public long getEliteGenerator() {
      return eliteGenerator_;
    }
    /**
     * <code>optional uint64 eliteGenerator = 6;</code>
     */
    public Builder setEliteGenerator(long value) {
      
      eliteGenerator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 eliteGenerator = 6;</code>
     */
    public Builder clearEliteGenerator() {
      
      eliteGenerator_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput> input_ =
      java.util.Collections.emptyList();
    private void ensureInputIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        input_ = new java.util.ArrayList<enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput>(input_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInputOrBuilder> inputBuilder_;

    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput> getInputList() {
      if (inputBuilder_ == null) {
        return java.util.Collections.unmodifiableList(input_);
      } else {
        return inputBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public int getInputCount() {
      if (inputBuilder_ == null) {
        return input_.size();
      } else {
        return inputBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput getInput(int index) {
      if (inputBuilder_ == null) {
        return input_.get(index);
      } else {
        return inputBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder setInput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput value) {
      if (inputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputIsMutable();
        input_.set(index, value);
        onChanged();
      } else {
        inputBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder setInput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder builderForValue) {
      if (inputBuilder_ == null) {
        ensureInputIsMutable();
        input_.set(index, builderForValue.build());
        onChanged();
      } else {
        inputBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder addInput(enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput value) {
      if (inputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputIsMutable();
        input_.add(value);
        onChanged();
      } else {
        inputBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder addInput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput value) {
      if (inputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInputIsMutable();
        input_.add(index, value);
        onChanged();
      } else {
        inputBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder addInput(
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder builderForValue) {
      if (inputBuilder_ == null) {
        ensureInputIsMutable();
        input_.add(builderForValue.build());
        onChanged();
      } else {
        inputBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder addInput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder builderForValue) {
      if (inputBuilder_ == null) {
        ensureInputIsMutable();
        input_.add(index, builderForValue.build());
        onChanged();
      } else {
        inputBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder addAllInput(
        java.lang.Iterable<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput> values) {
      if (inputBuilder_ == null) {
        ensureInputIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, input_);
        onChanged();
      } else {
        inputBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder clearInput() {
      if (inputBuilder_ == null) {
        input_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        inputBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public Builder removeInput(int index) {
      if (inputBuilder_ == null) {
        ensureInputIsMutable();
        input_.remove(index);
        onChanged();
      } else {
        inputBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder getInputBuilder(
        int index) {
      return getInputFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobInputOrBuilder getInputOrBuilder(
        int index) {
      if (inputBuilder_ == null) {
        return input_.get(index);  } else {
        return inputBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public java.util.List<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobInputOrBuilder> 
         getInputOrBuilderList() {
      if (inputBuilder_ != null) {
        return inputBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(input_);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder addInputBuilder() {
      return getInputFieldBuilder().addBuilder(
          enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder addInputBuilder(
        int index) {
      return getInputFieldBuilder().addBuilder(
          index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobInput input = 7;</code>
     */
    public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder> 
         getInputBuilderList() {
      return getInputFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInputOrBuilder> 
        getInputFieldBuilder() {
      if (inputBuilder_ == null) {
        inputBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInput.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobInputOrBuilder>(
                input_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      return inputBuilder_;
    }

    private java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput> output_ =
      java.util.Collections.emptyList();
    private void ensureOutputIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        output_ = new java.util.ArrayList<enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput>(output_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutputOrBuilder> outputBuilder_;

    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput> getOutputList() {
      if (outputBuilder_ == null) {
        return java.util.Collections.unmodifiableList(output_);
      } else {
        return outputBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public int getOutputCount() {
      if (outputBuilder_ == null) {
        return output_.size();
      } else {
        return outputBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput getOutput(int index) {
      if (outputBuilder_ == null) {
        return output_.get(index);
      } else {
        return outputBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder setOutput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput value) {
      if (outputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutputIsMutable();
        output_.set(index, value);
        onChanged();
      } else {
        outputBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder setOutput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder builderForValue) {
      if (outputBuilder_ == null) {
        ensureOutputIsMutable();
        output_.set(index, builderForValue.build());
        onChanged();
      } else {
        outputBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder addOutput(enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput value) {
      if (outputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutputIsMutable();
        output_.add(value);
        onChanged();
      } else {
        outputBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder addOutput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput value) {
      if (outputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOutputIsMutable();
        output_.add(index, value);
        onChanged();
      } else {
        outputBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder addOutput(
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder builderForValue) {
      if (outputBuilder_ == null) {
        ensureOutputIsMutable();
        output_.add(builderForValue.build());
        onChanged();
      } else {
        outputBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder addOutput(
        int index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder builderForValue) {
      if (outputBuilder_ == null) {
        ensureOutputIsMutable();
        output_.add(index, builderForValue.build());
        onChanged();
      } else {
        outputBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder addAllOutput(
        java.lang.Iterable<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput> values) {
      if (outputBuilder_ == null) {
        ensureOutputIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, output_);
        onChanged();
      } else {
        outputBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder clearOutput() {
      if (outputBuilder_ == null) {
        output_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        outputBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public Builder removeOutput(int index) {
      if (outputBuilder_ == null) {
        ensureOutputIsMutable();
        output_.remove(index);
        onChanged();
      } else {
        outputBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder getOutputBuilder(
        int index) {
      return getOutputFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutputOrBuilder getOutputOrBuilder(
        int index) {
      if (outputBuilder_ == null) {
        return output_.get(index);  } else {
        return outputBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public java.util.List<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutputOrBuilder> 
         getOutputOrBuilderList() {
      if (outputBuilder_ != null) {
        return outputBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(output_);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder addOutputBuilder() {
      return getOutputFieldBuilder().addBuilder(
          enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder addOutputBuilder(
        int index) {
      return getOutputFieldBuilder().addBuilder(
          index, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogTrainJobOutput output = 8;</code>
     */
    public java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder> 
         getOutputBuilderList() {
      return getOutputFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutputOrBuilder> 
        getOutputFieldBuilder() {
      if (outputBuilder_ == null) {
        outputBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutput.Builder, enn.monitor.log.train.proto.EnnMonitorLogTrainJobOutputOrBuilder>(
                output_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        output_ = null;
      }
      return outputBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EnnMonitorLogTrainJob)
  }

  // @@protoc_insertion_point(class_scope:EnnMonitorLogTrainJob)
  private static final enn.monitor.log.train.proto.EnnMonitorLogTrainJob DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new enn.monitor.log.train.proto.EnnMonitorLogTrainJob();
  }

  public static enn.monitor.log.train.proto.EnnMonitorLogTrainJob getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnnMonitorLogTrainJob>
      PARSER = new com.google.protobuf.AbstractParser<EnnMonitorLogTrainJob>() {
    public EnnMonitorLogTrainJob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnnMonitorLogTrainJob(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnnMonitorLogTrainJob> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnnMonitorLogTrainJob> getParserForType() {
    return PARSER;
  }

  public enn.monitor.log.train.proto.EnnMonitorLogTrainJob getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

