// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/trainParameters.proto

package enn.monitor.log.train.proto;

public interface EnnMonitorLogTrainMasterGetJobRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorLogTrainMasterGetJobRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>optional string error = 2;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>repeated .EnnMonitorLogTrainJob trainJob = 4;</code>
   */
  java.util.List<enn.monitor.log.train.proto.EnnMonitorLogTrainJob> 
      getTrainJobList();
  /**
   * <code>repeated .EnnMonitorLogTrainJob trainJob = 4;</code>
   */
  enn.monitor.log.train.proto.EnnMonitorLogTrainJob getTrainJob(int index);
  /**
   * <code>repeated .EnnMonitorLogTrainJob trainJob = 4;</code>
   */
  int getTrainJobCount();
  /**
   * <code>repeated .EnnMonitorLogTrainJob trainJob = 4;</code>
   */
  java.util.List<? extends enn.monitor.log.train.proto.EnnMonitorLogTrainJobOrBuilder> 
      getTrainJobOrBuilderList();
  /**
   * <code>repeated .EnnMonitorLogTrainJob trainJob = 4;</code>
   */
  enn.monitor.log.train.proto.EnnMonitorLogTrainJobOrBuilder getTrainJobOrBuilder(
      int index);
}
