// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logAnalyseTermParameters.proto

package enn.monitor.log.config.analyse.term.parameters;

public final class EnnMonitorLogConfigAnalyseTermParameters {
  private EnnMonitorLogConfigAnalyseTermParameters() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermGetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermGetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermCreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorLogConfigAnalyseTermDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorLogConfigAnalyseTermDeleteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'protobuf/logAnalyseTermParameters.prot" +
      "o\"\341\001\n#EnnMonitorLogConfigAnalyseTermTabl" +
      "e\022\n\n\002id\030\001 \001(\004\022\031\n\021belongToServiceId\030\002 \001(\004" +
      "\022\026\n\016analyseTermKey\030\003 \001(\t\022\017\n\007addTerm\030\004 \001(" +
      "\t\022\022\n\nfilterTerm\030\005 \001(\t\022\022\n\ncreateTime\030\006 \001(" +
      "\004\022\026\n\016lastUpdateTime\030\007 \001(\004\022\022\n\ncreateUser\030" +
      "\010 \001(\t\022\026\n\016lastUpdateUser\030\t \001(\t\"}\n(EnnMoni" +
      "torLogConfigAnalyseTermGetRequest\022\n\n\002id\030" +
      "\001 \001(\004\022\031\n\021belongToServiceId\030\002 \001(\004\022\022\n\ncrea" +
      "teUser\030\003 \001(\t\022\026\n\016lastUpdateUser\030\004 \001(\t\"\215\001\n",
      ")EnnMonitorLogConfigAnalyseTermGetRespon" +
      "se\022\021\n\tisSuccess\030\001 \001(\010\022>\n\020analyseTermTabl" +
      "e\030\002 \003(\0132$.EnnMonitorLogConfigAnalyseTerm" +
      "Table\022\r\n\005error\030\003 \001(\t\"\201\001\n+EnnMonitorLogCo" +
      "nfigAnalyseTermCreateRequest\022\017\n\007addTerm\030" +
      "\001 \001(\t\022\022\n\nfilterTerm\030\002 \001(\t\022\031\n\021belongToSer" +
      "viceId\030\003 \001(\004\022\022\n\ncreateUser\030\004 \001(\t\"P\n,EnnM" +
      "onitorLogConfigAnalyseTermCreateResponse" +
      "\022\021\n\tisSuccess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\"\221\001\n+E" +
      "nnMonitorLogConfigAnalyseTermUpdateReque",
      "st\022\n\n\002id\030\001 \001(\004\022\017\n\007addTerm\030\002 \001(\t\022\022\n\nfilte" +
      "rTerm\030\003 \001(\t\022\031\n\021belongToServiceId\030\004 \001(\004\022\026" +
      "\n\016lastUpdateUser\030\005 \001(\t\"P\n,EnnMonitorLogC" +
      "onfigAnalyseTermUpdateResponse\022\021\n\tisSucc" +
      "ess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\"9\n+EnnMonitorLo" +
      "gConfigAnalyseTermDeleteRequest\022\n\n\002id\030\001 " +
      "\001(\004\"P\n,EnnMonitorLogConfigAnalyseTermDel" +
      "eteResponse\022\021\n\tisSuccess\030\001 \001(\010\022\r\n\005error\030" +
      "\002 \001(\tB\\\n.enn.monitor.log.config.analyse." +
      "term.parametersB(EnnMonitorLogConfigAnal",
      "yseTermParametersP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnnMonitorLogConfigAnalyseTermTable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnnMonitorLogConfigAnalyseTermTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermTable_descriptor,
        new java.lang.String[] { "Id", "BelongToServiceId", "AnalyseTermKey", "AddTerm", "FilterTerm", "CreateTime", "LastUpdateTime", "CreateUser", "LastUpdateUser", });
    internal_static_EnnMonitorLogConfigAnalyseTermGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnnMonitorLogConfigAnalyseTermGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermGetRequest_descriptor,
        new java.lang.String[] { "Id", "BelongToServiceId", "CreateUser", "LastUpdateUser", });
    internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "AnalyseTermTable", "Error", });
    internal_static_EnnMonitorLogConfigAnalyseTermCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EnnMonitorLogConfigAnalyseTermCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermCreateRequest_descriptor,
        new java.lang.String[] { "AddTerm", "FilterTerm", "BelongToServiceId", "CreateUser", });
    internal_static_EnnMonitorLogConfigAnalyseTermCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EnnMonitorLogConfigAnalyseTermCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermCreateResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", });
    internal_static_EnnMonitorLogConfigAnalyseTermUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_EnnMonitorLogConfigAnalyseTermUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermUpdateRequest_descriptor,
        new java.lang.String[] { "Id", "AddTerm", "FilterTerm", "BelongToServiceId", "LastUpdateUser", });
    internal_static_EnnMonitorLogConfigAnalyseTermUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EnnMonitorLogConfigAnalyseTermUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermUpdateResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", });
    internal_static_EnnMonitorLogConfigAnalyseTermDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EnnMonitorLogConfigAnalyseTermDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermDeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_EnnMonitorLogConfigAnalyseTermDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_EnnMonitorLogConfigAnalyseTermDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorLogConfigAnalyseTermDeleteResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
