// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logAnalyseTermParameters.proto

package enn.monitor.log.config.analyse.term.parameters;

public interface EnnMonitorLogConfigAnalyseTermCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorLogConfigAnalyseTermCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string addTerm = 1;</code>
   */
  java.lang.String getAddTerm();
  /**
   * <code>optional string addTerm = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddTermBytes();

  /**
   * <code>optional string filterTerm = 2;</code>
   */
  java.lang.String getFilterTerm();
  /**
   * <code>optional string filterTerm = 2;</code>
   */
  com.google.protobuf.ByteString
      getFilterTermBytes();

  /**
   * <code>optional uint64 belongToServiceId = 3;</code>
   */
  long getBelongToServiceId();

  /**
   * <code>optional string createUser = 4;</code>
   */
  java.lang.String getCreateUser();
  /**
   * <code>optional string createUser = 4;</code>
   */
  com.google.protobuf.ByteString
      getCreateUserBytes();
}
