// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logAnalyseTermParameters.proto

package enn.monitor.log.config.analyse.term.parameters;

/**
 * Protobuf type {@code EnnMonitorLogConfigAnalyseTermGetResponse}
 */
public  final class EnnMonitorLogConfigAnalyseTermGetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnnMonitorLogConfigAnalyseTermGetResponse)
    EnnMonitorLogConfigAnalyseTermGetResponseOrBuilder {
  // Use EnnMonitorLogConfigAnalyseTermGetResponse.newBuilder() to construct.
  private EnnMonitorLogConfigAnalyseTermGetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnnMonitorLogConfigAnalyseTermGetResponse() {
    isSuccess_ = false;
    analyseTermTable_ = java.util.Collections.emptyList();
    error_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EnnMonitorLogConfigAnalyseTermGetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isSuccess_ = input.readBool();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              analyseTermTable_ = new java.util.ArrayList<enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable>();
              mutable_bitField0_ |= 0x00000002;
            }
            analyseTermTable_.add(
                input.readMessage(enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            error_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        analyseTermTable_ = java.util.Collections.unmodifiableList(analyseTermTable_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermParameters.internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermParameters.internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse.class, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ISSUCCESS_FIELD_NUMBER = 1;
  private boolean isSuccess_;
  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  public boolean getIsSuccess() {
    return isSuccess_;
  }

  public static final int ANALYSETERMTABLE_FIELD_NUMBER = 2;
  private java.util.List<enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable> analyseTermTable_;
  /**
   * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
   */
  public java.util.List<enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable> getAnalyseTermTableList() {
    return analyseTermTable_;
  }
  /**
   * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
   */
  public java.util.List<? extends enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTableOrBuilder> 
      getAnalyseTermTableOrBuilderList() {
    return analyseTermTable_;
  }
  /**
   * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
   */
  public int getAnalyseTermTableCount() {
    return analyseTermTable_.size();
  }
  /**
   * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
   */
  public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable getAnalyseTermTable(int index) {
    return analyseTermTable_.get(index);
  }
  /**
   * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
   */
  public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTableOrBuilder getAnalyseTermTableOrBuilder(
      int index) {
    return analyseTermTable_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  private volatile java.lang.Object error_;
  /**
   * <code>optional string error = 3;</code>
   */
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>optional string error = 3;</code>
   */
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isSuccess_ != false) {
      output.writeBool(1, isSuccess_);
    }
    for (int i = 0; i < analyseTermTable_.size(); i++) {
      output.writeMessage(2, analyseTermTable_.get(i));
    }
    if (!getErrorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, error_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isSuccess_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isSuccess_);
    }
    for (int i = 0; i < analyseTermTable_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, analyseTermTable_.get(i));
    }
    if (!getErrorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, error_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse)) {
      return super.equals(obj);
    }
    enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse other = (enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse) obj;

    boolean result = true;
    result = result && (getIsSuccess()
        == other.getIsSuccess());
    result = result && getAnalyseTermTableList()
        .equals(other.getAnalyseTermTableList());
    result = result && getError()
        .equals(other.getError());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSuccess());
    if (getAnalyseTermTableCount() > 0) {
      hash = (37 * hash) + ANALYSETERMTABLE_FIELD_NUMBER;
      hash = (53 * hash) + getAnalyseTermTableList().hashCode();
    }
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EnnMonitorLogConfigAnalyseTermGetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnnMonitorLogConfigAnalyseTermGetResponse)
      enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermParameters.internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermParameters.internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse.class, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse.Builder.class);
    }

    // Construct using enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAnalyseTermTableFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      isSuccess_ = false;

      if (analyseTermTableBuilder_ == null) {
        analyseTermTable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        analyseTermTableBuilder_.clear();
      }
      error_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermParameters.internal_static_EnnMonitorLogConfigAnalyseTermGetResponse_descriptor;
    }

    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse getDefaultInstanceForType() {
      return enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse.getDefaultInstance();
    }

    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse build() {
      enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse buildPartial() {
      enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse result = new enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.isSuccess_ = isSuccess_;
      if (analyseTermTableBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          analyseTermTable_ = java.util.Collections.unmodifiableList(analyseTermTable_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.analyseTermTable_ = analyseTermTable_;
      } else {
        result.analyseTermTable_ = analyseTermTableBuilder_.build();
      }
      result.error_ = error_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse) {
        return mergeFrom((enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse other) {
      if (other == enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse.getDefaultInstance()) return this;
      if (other.getIsSuccess() != false) {
        setIsSuccess(other.getIsSuccess());
      }
      if (analyseTermTableBuilder_ == null) {
        if (!other.analyseTermTable_.isEmpty()) {
          if (analyseTermTable_.isEmpty()) {
            analyseTermTable_ = other.analyseTermTable_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAnalyseTermTableIsMutable();
            analyseTermTable_.addAll(other.analyseTermTable_);
          }
          onChanged();
        }
      } else {
        if (!other.analyseTermTable_.isEmpty()) {
          if (analyseTermTableBuilder_.isEmpty()) {
            analyseTermTableBuilder_.dispose();
            analyseTermTableBuilder_ = null;
            analyseTermTable_ = other.analyseTermTable_;
            bitField0_ = (bitField0_ & ~0x00000002);
            analyseTermTableBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAnalyseTermTableFieldBuilder() : null;
          } else {
            analyseTermTableBuilder_.addAllMessages(other.analyseTermTable_);
          }
        }
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean isSuccess_ ;
    /**
     * <code>optional bool isSuccess = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }
    /**
     * <code>optional bool isSuccess = 1;</code>
     */
    public Builder setIsSuccess(boolean value) {
      
      isSuccess_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isSuccess = 1;</code>
     */
    public Builder clearIsSuccess() {
      
      isSuccess_ = false;
      onChanged();
      return this;
    }

    private java.util.List<enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable> analyseTermTable_ =
      java.util.Collections.emptyList();
    private void ensureAnalyseTermTableIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        analyseTermTable_ = new java.util.ArrayList<enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable>(analyseTermTable_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTableOrBuilder> analyseTermTableBuilder_;

    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public java.util.List<enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable> getAnalyseTermTableList() {
      if (analyseTermTableBuilder_ == null) {
        return java.util.Collections.unmodifiableList(analyseTermTable_);
      } else {
        return analyseTermTableBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public int getAnalyseTermTableCount() {
      if (analyseTermTableBuilder_ == null) {
        return analyseTermTable_.size();
      } else {
        return analyseTermTableBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable getAnalyseTermTable(int index) {
      if (analyseTermTableBuilder_ == null) {
        return analyseTermTable_.get(index);
      } else {
        return analyseTermTableBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder setAnalyseTermTable(
        int index, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable value) {
      if (analyseTermTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnalyseTermTableIsMutable();
        analyseTermTable_.set(index, value);
        onChanged();
      } else {
        analyseTermTableBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder setAnalyseTermTable(
        int index, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder builderForValue) {
      if (analyseTermTableBuilder_ == null) {
        ensureAnalyseTermTableIsMutable();
        analyseTermTable_.set(index, builderForValue.build());
        onChanged();
      } else {
        analyseTermTableBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder addAnalyseTermTable(enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable value) {
      if (analyseTermTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnalyseTermTableIsMutable();
        analyseTermTable_.add(value);
        onChanged();
      } else {
        analyseTermTableBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder addAnalyseTermTable(
        int index, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable value) {
      if (analyseTermTableBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAnalyseTermTableIsMutable();
        analyseTermTable_.add(index, value);
        onChanged();
      } else {
        analyseTermTableBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder addAnalyseTermTable(
        enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder builderForValue) {
      if (analyseTermTableBuilder_ == null) {
        ensureAnalyseTermTableIsMutable();
        analyseTermTable_.add(builderForValue.build());
        onChanged();
      } else {
        analyseTermTableBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder addAnalyseTermTable(
        int index, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder builderForValue) {
      if (analyseTermTableBuilder_ == null) {
        ensureAnalyseTermTableIsMutable();
        analyseTermTable_.add(index, builderForValue.build());
        onChanged();
      } else {
        analyseTermTableBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder addAllAnalyseTermTable(
        java.lang.Iterable<? extends enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable> values) {
      if (analyseTermTableBuilder_ == null) {
        ensureAnalyseTermTableIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, analyseTermTable_);
        onChanged();
      } else {
        analyseTermTableBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder clearAnalyseTermTable() {
      if (analyseTermTableBuilder_ == null) {
        analyseTermTable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        analyseTermTableBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public Builder removeAnalyseTermTable(int index) {
      if (analyseTermTableBuilder_ == null) {
        ensureAnalyseTermTableIsMutable();
        analyseTermTable_.remove(index);
        onChanged();
      } else {
        analyseTermTableBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder getAnalyseTermTableBuilder(
        int index) {
      return getAnalyseTermTableFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTableOrBuilder getAnalyseTermTableOrBuilder(
        int index) {
      if (analyseTermTableBuilder_ == null) {
        return analyseTermTable_.get(index);  } else {
        return analyseTermTableBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public java.util.List<? extends enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTableOrBuilder> 
         getAnalyseTermTableOrBuilderList() {
      if (analyseTermTableBuilder_ != null) {
        return analyseTermTableBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(analyseTermTable_);
      }
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder addAnalyseTermTableBuilder() {
      return getAnalyseTermTableFieldBuilder().addBuilder(
          enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder addAnalyseTermTableBuilder(
        int index) {
      return getAnalyseTermTableFieldBuilder().addBuilder(
          index, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.getDefaultInstance());
    }
    /**
     * <code>repeated .EnnMonitorLogConfigAnalyseTermTable analyseTermTable = 2;</code>
     */
    public java.util.List<enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder> 
         getAnalyseTermTableBuilderList() {
      return getAnalyseTermTableFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTableOrBuilder> 
        getAnalyseTermTableFieldBuilder() {
      if (analyseTermTableBuilder_ == null) {
        analyseTermTableBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTable.Builder, enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermTableOrBuilder>(
                analyseTermTable_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        analyseTermTable_ = null;
      }
      return analyseTermTableBuilder_;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>optional string error = 3;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public Builder clearError() {
      
      error_ = getDefaultInstance().getError();
      onChanged();
      return this;
    }
    /**
     * <code>optional string error = 3;</code>
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      error_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EnnMonitorLogConfigAnalyseTermGetResponse)
  }

  // @@protoc_insertion_point(class_scope:EnnMonitorLogConfigAnalyseTermGetResponse)
  private static final enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse();
  }

  public static enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnnMonitorLogConfigAnalyseTermGetResponse>
      PARSER = new com.google.protobuf.AbstractParser<EnnMonitorLogConfigAnalyseTermGetResponse>() {
    public EnnMonitorLogConfigAnalyseTermGetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnnMonitorLogConfigAnalyseTermGetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnnMonitorLogConfigAnalyseTermGetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnnMonitorLogConfigAnalyseTermGetResponse> getParserForType() {
    return PARSER;
  }

  public enn.monitor.log.config.analyse.term.parameters.EnnMonitorLogConfigAnalyseTermGetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

