// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logCommonServer.proto

package enn.monitor.log.config.common.server;

public final class EnnMonitorLogConfigCommonConnection {
  private EnnMonitorLogConfigCommonConnection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036protobuf/logCommonServer.proto\032\"protob" +
      "uf/logCommonParameters.proto2\206\001\n\037EnnMoni" +
      "torLogConfigCommonServer\022c\n\nGetBatchId\022+" +
      ".EnnMonitorLogConfigCommonBatchIdGetRequ" +
      "est\032&.EnnMonitorLogConfigBatchIdGetRespo" +
      "nse\"\000BM\n$enn.monitor.log.config.common.s" +
      "erverB#EnnMonitorLogConfigCommonConnecti" +
      "onP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          enn.monitor.log.config.common.parameters.EnnMonitorLogConfigTemplateTermTermParameters.getDescriptor(),
        }, assigner);
    enn.monitor.log.config.common.parameters.EnnMonitorLogConfigTemplateTermTermParameters.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
