gradle \
enn-monitor-log:enn-monitor-log-archive-proto:upload \
enn-monitor-log:enn-monitor-log-normalizing:enn-monitor-log-normalizing-proto:upload \
enn-monitor-log:enn-monitor-log-normalizing:enn-monitor-log-normalizing-client:upload \
enn-monitor-log:enn-monitor-log-config:enn-monitor-log-config-proto:upload \
enn-monitor-log:enn-monitor-log-config:enn-monitor-log-config-client:upload \
enn-monitor-log:enn-monitor-log-config:enn-monitor-log-config-proto:upload \
enn-monitor-log:enn-monitor-log-config:enn-monitor-log-config-gateway-proto:upload \
enn-monitor-log:enn-monitor-log-config:enn-monitor-log-config-gateway-client:upload \
enn-monitor-log:enn-monitor-log-config:enn-monitor-log-config-cache-proto:upload \
enn-monitor-log:enn-monitor-log-config:enn-monitor-log-config-cache-client:upload \
enn-monitor-log:enn-monitor-log-train:enn-monitor-log-train-common:upload \
enn-monitor-log:enn-monitor-log-train:enn-monitor-log-train-proto:upload \
enn-monitor-log:enn-monitor-log-train:enn-monitor-log-train-master-client:upload \
enn-monitor-log:enn-monitor-log-analyse:enn-monitor-log-analyse-template-client:upload \
enn-monitor-log:enn-monitor-log-analyse:enn-monitor-log-analyse-storage-proto:upload \
enn-monitor-log:enn-monitor-log-analyse:enn-monitor-log-analyse-storage-client:upload \
enn-monitor-log:enn-monitor-log-analyse:enn-monitor-log-analyse-storage-util:upload \
enn-monitor-log:enn-monitor-log-analyse:enn-monitor-log-analyse-proto:upload \
-x javadoc
