// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logConfigCacheParameter.proto

package enn.monitor.log.config.cache.parameters;

public interface EnnMonitorLogConfigCacheResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorLogConfigCacheResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>optional string tag = 2;</code>
   */
  java.lang.String getTag();
  /**
   * <code>optional string tag = 2;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>optional string error = 3;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
