// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logEventParameters.proto

package enn.monitor.log.config.event.parameters;

public interface EnnMonitorLogConfigEventGetMaxDeletedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorLogConfigEventGetMaxDeletedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>optional string error = 2;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>optional uint64 seqNo = 3;</code>
   */
  long getSeqNo();
}
