// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/logEventParameters.proto

package enn.monitor.log.config.event.parameters;

public interface EnnMonitorLogConfigEventGetDeletedDataListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorLogConfigEventGetDeletedDataListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>optional string error = 2;</code>
   */
  java.lang.String getError();
  /**
   * <code>optional string error = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>repeated .EnnMonitorLogConfigEventGetDeletedData deletedDataList = 3;</code>
   */
  java.util.List<enn.monitor.log.config.event.parameters.EnnMonitorLogConfigEventGetDeletedData> 
      getDeletedDataListList();
  /**
   * <code>repeated .EnnMonitorLogConfigEventGetDeletedData deletedDataList = 3;</code>
   */
  enn.monitor.log.config.event.parameters.EnnMonitorLogConfigEventGetDeletedData getDeletedDataList(int index);
  /**
   * <code>repeated .EnnMonitorLogConfigEventGetDeletedData deletedDataList = 3;</code>
   */
  int getDeletedDataListCount();
  /**
   * <code>repeated .EnnMonitorLogConfigEventGetDeletedData deletedDataList = 3;</code>
   */
  java.util.List<? extends enn.monitor.log.config.event.parameters.EnnMonitorLogConfigEventGetDeletedDataOrBuilder> 
      getDeletedDataListOrBuilderList();
  /**
   * <code>repeated .EnnMonitorLogConfigEventGetDeletedData deletedDataList = 3;</code>
   */
  enn.monitor.log.config.event.parameters.EnnMonitorLogConfigEventGetDeletedDataOrBuilder getDeletedDataListOrBuilder(
      int index);
}
