// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/clusterParameters.proto

package enn.monitor.config.cluster.parameters;

/**
 * <pre>
 * get valid data list
 * </pre>
 *
 * Protobuf type {@code EnnMonitorConfigClusterGetValidDataListRequest}
 */
public  final class EnnMonitorConfigClusterGetValidDataListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnnMonitorConfigClusterGetValidDataListRequest)
    EnnMonitorConfigClusterGetValidDataListRequestOrBuilder {
  // Use EnnMonitorConfigClusterGetValidDataListRequest.newBuilder() to construct.
  private EnnMonitorConfigClusterGetValidDataListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnnMonitorConfigClusterGetValidDataListRequest() {
    startSeqNo_ = 0L;
    batchNum_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private EnnMonitorConfigClusterGetValidDataListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            startSeqNo_ = input.readUInt64();
            break;
          }
          case 16: {

            batchNum_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterParameters.internal_static_EnnMonitorConfigClusterGetValidDataListRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterParameters.internal_static_EnnMonitorConfigClusterGetValidDataListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest.class, enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest.Builder.class);
  }

  public static final int STARTSEQNO_FIELD_NUMBER = 1;
  private long startSeqNo_;
  /**
   * <code>optional uint64 startSeqNo = 1;</code>
   */
  public long getStartSeqNo() {
    return startSeqNo_;
  }

  public static final int BATCHNUM_FIELD_NUMBER = 2;
  private int batchNum_;
  /**
   * <code>optional uint32 batchNum = 2;</code>
   */
  public int getBatchNum() {
    return batchNum_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startSeqNo_ != 0L) {
      output.writeUInt64(1, startSeqNo_);
    }
    if (batchNum_ != 0) {
      output.writeUInt32(2, batchNum_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startSeqNo_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, startSeqNo_);
    }
    if (batchNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, batchNum_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest)) {
      return super.equals(obj);
    }
    enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest other = (enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest) obj;

    boolean result = true;
    result = result && (getStartSeqNo()
        == other.getStartSeqNo());
    result = result && (getBatchNum()
        == other.getBatchNum());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + STARTSEQNO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartSeqNo());
    hash = (37 * hash) + BATCHNUM_FIELD_NUMBER;
    hash = (53 * hash) + getBatchNum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * get valid data list
   * </pre>
   *
   * Protobuf type {@code EnnMonitorConfigClusterGetValidDataListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnnMonitorConfigClusterGetValidDataListRequest)
      enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterParameters.internal_static_EnnMonitorConfigClusterGetValidDataListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterParameters.internal_static_EnnMonitorConfigClusterGetValidDataListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest.class, enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest.Builder.class);
    }

    // Construct using enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      startSeqNo_ = 0L;

      batchNum_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterParameters.internal_static_EnnMonitorConfigClusterGetValidDataListRequest_descriptor;
    }

    public enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest getDefaultInstanceForType() {
      return enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest.getDefaultInstance();
    }

    public enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest build() {
      enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest buildPartial() {
      enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest result = new enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest(this);
      result.startSeqNo_ = startSeqNo_;
      result.batchNum_ = batchNum_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest) {
        return mergeFrom((enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest other) {
      if (other == enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest.getDefaultInstance()) return this;
      if (other.getStartSeqNo() != 0L) {
        setStartSeqNo(other.getStartSeqNo());
      }
      if (other.getBatchNum() != 0) {
        setBatchNum(other.getBatchNum());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long startSeqNo_ ;
    /**
     * <code>optional uint64 startSeqNo = 1;</code>
     */
    public long getStartSeqNo() {
      return startSeqNo_;
    }
    /**
     * <code>optional uint64 startSeqNo = 1;</code>
     */
    public Builder setStartSeqNo(long value) {
      
      startSeqNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 startSeqNo = 1;</code>
     */
    public Builder clearStartSeqNo() {
      
      startSeqNo_ = 0L;
      onChanged();
      return this;
    }

    private int batchNum_ ;
    /**
     * <code>optional uint32 batchNum = 2;</code>
     */
    public int getBatchNum() {
      return batchNum_;
    }
    /**
     * <code>optional uint32 batchNum = 2;</code>
     */
    public Builder setBatchNum(int value) {
      
      batchNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 batchNum = 2;</code>
     */
    public Builder clearBatchNum() {
      
      batchNum_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:EnnMonitorConfigClusterGetValidDataListRequest)
  }

  // @@protoc_insertion_point(class_scope:EnnMonitorConfigClusterGetValidDataListRequest)
  private static final enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest();
  }

  public static enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnnMonitorConfigClusterGetValidDataListRequest>
      PARSER = new com.google.protobuf.AbstractParser<EnnMonitorConfigClusterGetValidDataListRequest>() {
    public EnnMonitorConfigClusterGetValidDataListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnnMonitorConfigClusterGetValidDataListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnnMonitorConfigClusterGetValidDataListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnnMonitorConfigClusterGetValidDataListRequest> getParserForType() {
    return PARSER;
  }

  public enn.monitor.config.cluster.parameters.EnnMonitorConfigClusterGetValidDataListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

