// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/clusterParameters.proto

package enn.monitor.config.cluster.parameters;

public final class EnnMonitorConfigClusterParameters {
  private EnnMonitorConfigClusterParameters() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterCreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterDeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetMaxDeletedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetMaxDeletedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetMaxDeletedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetMaxDeletedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetValidDataListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetValidDataListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetValidDataListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetValidDataListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetDeletedDataListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetDeletedDataListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetDeletedData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetDeletedData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterGetDeletedDataListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterGetDeletedDataListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterExistClusterNameOrNotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterExistClusterNameOrNotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnnMonitorConfigClusterExistClusterNameOrNotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnnMonitorConfigClusterExistClusterNameOrNotResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n protobuf/clusterParameters.proto\"\326\001\n\034E" +
      "nnMonitorConfigClusterTable\022\n\n\002id\030\001 \001(\004\022" +
      "\r\n\005seqNo\030\002 \001(\004\022.\n\006status\030\003 \001(\0162\036.EnnMoni" +
      "torConfigClusterStatus\022\023\n\013clusterName\030\004 " +
      "\001(\t\022\022\n\ncreateTime\030\005 \001(\004\022\026\n\016lastUpdateTim" +
      "e\030\006 \001(\004\022\022\n\ncreateUser\030\007 \001(\t\022\026\n\016lastUpdat" +
      "eUser\030\010 \001(\t\"\240\001\n!EnnMonitorConfigClusterG" +
      "etRequest\022\n\n\002id\030\001 \001(\004\022.\n\006status\030\002 \001(\0162\036." +
      "EnnMonitorConfigClusterStatus\022\023\n\013cluster" +
      "Name\030\003 \001(\t\022\022\n\ncreateUser\030\004 \001(\t\022\026\n\016lastUp",
      "dateUser\030\005 \001(\t\"{\n\"EnnMonitorConfigCluste" +
      "rGetResponse\022\021\n\tisSuccess\030\001 \001(\010\0223\n\014clust" +
      "erTable\030\002 \003(\0132\035.EnnMonitorConfigClusterT" +
      "able\022\r\n\005error\030\003 \001(\t\"O\n$EnnMonitorConfigC" +
      "lusterCreateRequest\022\023\n\013clusterName\030\001 \001(\t" +
      "\022\022\n\ncreateUser\030\002 \001(\t\"I\n%EnnMonitorConfig" +
      "ClusterCreateResponse\022\021\n\tisSuccess\030\001 \001(\010" +
      "\022\r\n\005error\030\002 \001(\t\"\217\001\n$EnnMonitorConfigClus" +
      "terUpdateRequest\022\n\n\002id\030\001 \001(\004\022.\n\006status\030\002" +
      " \001(\0162\036.EnnMonitorConfigClusterStatus\022\023\n\013",
      "clusterName\030\003 \001(\t\022\026\n\016lastUpdateUser\030\004 \001(" +
      "\t\"I\n%EnnMonitorConfigClusterUpdateRespon" +
      "se\022\021\n\tisSuccess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\"J\n$" +
      "EnnMonitorConfigClusterDeleteRequest\022\n\n\002" +
      "id\030\001 \001(\004\022\026\n\016lastUpdateUser\030\002 \001(\t\"I\n%EnnM" +
      "onitorConfigClusterDeleteResponse\022\021\n\tisS" +
      "uccess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\"-\n+EnnMonito" +
      "rConfigClusterGetMaxDeletedRequest\"_\n,En" +
      "nMonitorConfigClusterGetMaxDeletedRespon" +
      "se\022\021\n\tisSuccess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\022\r\n\005",
      "seqNo\030\003 \001(\004\"V\n.EnnMonitorConfigClusterGe" +
      "tValidDataListRequest\022\022\n\nstartSeqNo\030\001 \001(" +
      "\004\022\020\n\010batchNum\030\002 \001(\r\"\214\001\n/EnnMonitorConfig" +
      "ClusterGetValidDataListResponse\022\021\n\tisSuc" +
      "cess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\0227\n\020clusterTabl" +
      "eList\030\003 \003(\0132\035.EnnMonitorConfigClusterTab" +
      "le\"X\n0EnnMonitorConfigClusterGetDeletedD" +
      "ataListRequest\022\022\n\nstartSeqNo\030\001 \001(\004\022\020\n\010ba" +
      "tchNum\030\002 \001(\r\"B\n%EnnMonitorConfigClusterG" +
      "etDeletedData\022\n\n\002id\030\001 \001(\004\022\r\n\005seqNo\030\002 \001(\004",
      "\"\226\001\n1EnnMonitorConfigClusterGetDeletedDa" +
      "taListResponse\022\021\n\tisSuccess\030\001 \001(\010\022\r\n\005err" +
      "or\030\002 \001(\t\022?\n\017deletedDataList\030\003 \003(\0132&.EnnM" +
      "onitorConfigClusterGetDeletedData\"J\n3Enn" +
      "MonitorConfigClusterExistClusterNameOrNo" +
      "tRequest\022\023\n\013clusterName\030\001 \001(\t\"X\n4EnnMoni" +
      "torConfigClusterExistClusterNameOrNotRes" +
      "ponse\022\021\n\tisSuccess\030\001 \001(\010\022\r\n\005error\030\002 \001(\t*" +
      "\\\n\035EnnMonitorConfigClusterStatus\022\022\n\016Clus" +
      "terDefault\020\000\022\022\n\016ClusterRunning\020\001\022\023\n\017Clus",
      "terDeleting\020\002BL\n%enn.monitor.config.clus" +
      "ter.parametersB!EnnMonitorConfigClusterP" +
      "arametersP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnnMonitorConfigClusterTable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnnMonitorConfigClusterTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterTable_descriptor,
        new java.lang.String[] { "Id", "SeqNo", "Status", "ClusterName", "CreateTime", "LastUpdateTime", "CreateUser", "LastUpdateUser", });
    internal_static_EnnMonitorConfigClusterGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnnMonitorConfigClusterGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetRequest_descriptor,
        new java.lang.String[] { "Id", "Status", "ClusterName", "CreateUser", "LastUpdateUser", });
    internal_static_EnnMonitorConfigClusterGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EnnMonitorConfigClusterGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "ClusterTable", "Error", });
    internal_static_EnnMonitorConfigClusterCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EnnMonitorConfigClusterCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterCreateRequest_descriptor,
        new java.lang.String[] { "ClusterName", "CreateUser", });
    internal_static_EnnMonitorConfigClusterCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EnnMonitorConfigClusterCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterCreateResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", });
    internal_static_EnnMonitorConfigClusterUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_EnnMonitorConfigClusterUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterUpdateRequest_descriptor,
        new java.lang.String[] { "Id", "Status", "ClusterName", "LastUpdateUser", });
    internal_static_EnnMonitorConfigClusterUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_EnnMonitorConfigClusterUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterUpdateResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", });
    internal_static_EnnMonitorConfigClusterDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_EnnMonitorConfigClusterDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterDeleteRequest_descriptor,
        new java.lang.String[] { "Id", "LastUpdateUser", });
    internal_static_EnnMonitorConfigClusterDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_EnnMonitorConfigClusterDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterDeleteResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", });
    internal_static_EnnMonitorConfigClusterGetMaxDeletedRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_EnnMonitorConfigClusterGetMaxDeletedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetMaxDeletedRequest_descriptor,
        new java.lang.String[] { });
    internal_static_EnnMonitorConfigClusterGetMaxDeletedResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_EnnMonitorConfigClusterGetMaxDeletedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetMaxDeletedResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", "SeqNo", });
    internal_static_EnnMonitorConfigClusterGetValidDataListRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_EnnMonitorConfigClusterGetValidDataListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetValidDataListRequest_descriptor,
        new java.lang.String[] { "StartSeqNo", "BatchNum", });
    internal_static_EnnMonitorConfigClusterGetValidDataListResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_EnnMonitorConfigClusterGetValidDataListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetValidDataListResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", "ClusterTableList", });
    internal_static_EnnMonitorConfigClusterGetDeletedDataListRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_EnnMonitorConfigClusterGetDeletedDataListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetDeletedDataListRequest_descriptor,
        new java.lang.String[] { "StartSeqNo", "BatchNum", });
    internal_static_EnnMonitorConfigClusterGetDeletedData_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_EnnMonitorConfigClusterGetDeletedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetDeletedData_descriptor,
        new java.lang.String[] { "Id", "SeqNo", });
    internal_static_EnnMonitorConfigClusterGetDeletedDataListResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_EnnMonitorConfigClusterGetDeletedDataListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterGetDeletedDataListResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", "DeletedDataList", });
    internal_static_EnnMonitorConfigClusterExistClusterNameOrNotRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_EnnMonitorConfigClusterExistClusterNameOrNotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterExistClusterNameOrNotRequest_descriptor,
        new java.lang.String[] { "ClusterName", });
    internal_static_EnnMonitorConfigClusterExistClusterNameOrNotResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_EnnMonitorConfigClusterExistClusterNameOrNotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnnMonitorConfigClusterExistClusterNameOrNotResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
