// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/clusterParameters.proto

package enn.monitor.config.cluster.parameters;

public interface EnnMonitorConfigClusterGetMaxDeletedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnnMonitorConfigClusterGetMaxDeletedRequest)
    com.google.protobuf.MessageOrBuilder {
}
